sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "8"
  - "10"
  - "11"
install: npm install
script: npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
